---
- name: Install postgres
  hosts: postgres-hosts
  vars_files: 
    - vars.yml

  roles:
    - role: install_postgres
      tags: install_postgres
    - role: open_firewalld_port
      tags: open_firewalld_port
    - role: set_up_replication
      tags: set_up_replication
