---
- name: Install postgres
  hosts: postgres-hosts
  pre_tasks:
    - name: Install pip
      ansible.builtin.dnf:
        name: python3-pip
        state: present
    - name: Install gcc
      ansible.builtin.dnf:
        name: gcc
        state: present
    - name: Install python3-devel
      ansible.builtin.dnf:
        name: python3-devel
        state: present
    - name: Enable CodeReady Builder repository
      community.general.dnf_config_manager:
        name: ol8_codeready_builder
        state: enabled
    - name: Add path to PATH
      ansible.builtin.lineinfile: 
        path: /etc/profile
        line: 'export PATH="$PATH:/usr/pgsql-15/bin"'
  tasks:
  - name: Install postgres repository
    ansible.builtin.dnf:
      name: 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm'
      state: present
      disable_gpg_check: true
  - name: Disable postgres built-in module
    ansible.builtin.command: dnf -qy module disable postgresql
  - name: Install postgres-15
    ansible.builtin.dnf:
      name: postgresql15-server
      state: present
  - name: Install psycopg2
    ansible.builtin.dnf:
      name: python3-psycopg2
      state: present
  - name: Start and enable only primary postgres host
    ansible.builtin.service:
      name: postgresql-15
      state: started
      enabled: yes
    when: inventory_hostname == "postgres-primary"